rws:
  be: http://localhost:8001/routes
  fe: http://localhost:8002/routes

ls:
  fe: http://localhost:8003/login
  signup: http://localhost:8003/login/signup
  login: http://localhost:8003/login/auth
  check: http://localhost:8003/check
